# Gaussian Elimination

We want to solve systems of equations of the form 

$$A x = b$$

where $A$ is an $n\times n$ matrix of known values, $b$ is a vector of length $n$ of known values and $x$ is a vector of length $n$ of unknown values.

We can solve this problem by expliciting finding the inverse matrix, $A^{-1}$. We saw in the lectures that if we use the matrix of cofactors method this is very inefficient, as the number of operations required grows as $n!$.

A more efficient method is Gaussian elimination. This notebook implements a version of this algorithm. The code below work on any sized matrix.

In [358]:
import numpy as np

In [359]:
def GaussianElimination(A, b, verboseLevel=0):
    n = A.shape[1]
    
    # Append the vector b as a column to the matrix A
    A1 = np.c_[A,b]
    
    if(verboseLevel >=1): print("A1 matrix =\n", A1, "\n")

    i = 0
    while i < n - 1:
        j = i+1
        while j < n:
            tmp = A1[i]*A1[j,i]/A1[i,i]
            if(verboseLevel >= 2): print("Row to subtract from a_%d" %j,"=", tmp)
            A1[j] = A1[j] - tmp
            j += 1
            
        if(verboseLevel >= 1): print("\nNew A1 matrix =\n", A1, "\n")
        i += 1
        
    # The matrix is now in upper-triangular form
    # Now we back substitute to find x
    
    x = np.zeros(n)
    
    i = n-1
    while i >= 0:
        j = i
        x[i] = A1[i,n]
        while j < n-1:
            x[i] -= A1[i,j+1]*x[j+1]
            j += 1
        x[i] = x[i]/A1[i,i]
        i -= 1
    
    return x

Let's first test the code on a $3\times 3$ matrix. I found testing on a small matrix like this was very useful to debug the code (it takes a while to get all the indexing correct).

In [360]:
# Define a matrix A, and a vector b
A = np.array([[1, 2, 3], [5, 6, 7], [1, 4, 5]], dtype='float')
b = np.array([3, 4 , 5])

# print out A and b (notice that '\n' creates a new line)
print("A =\n", A)
print("\nb =", b)

A =
 [[1. 2. 3.]
 [5. 6. 7.]
 [1. 4. 5.]]

b = [3 4 5]


The final argument to `GassianElimination()` is the `verboseLevel`. By default this is `0`. For higher values the code outputs more information about the steps it is taking.

In [361]:
GaussianElimination(A, b, 2)

A1 matrix =
 [[1. 2. 3. 3.]
 [5. 6. 7. 4.]
 [1. 4. 5. 5.]] 

Row to subtract from a_1 = [ 5. 10. 15. 15.]
Row to subtract from a_2 = [1. 2. 3. 3.]

New A1 matrix =
 [[  1.   2.   3.   3.]
 [  0.  -4.  -8. -11.]
 [  0.   2.   2.   2.]] 

Row to subtract from a_2 = [-0.   2.   4.   5.5]

New A1 matrix =
 [[  1.    2.    3.    3. ]
 [  0.   -4.   -8.  -11. ]
 [  0.    0.   -2.   -3.5]] 



array([-0.75, -0.75,  1.75])

The `GaussianElimination()` function works for any size of matrix. Let's test it on a larger one.