# Gaussian Elimination

We want to solve systems of equations of the form 

$$A x = b$$

where $A$ is an $n\times n$ matrix of known values, $b$ is a vector of length $n$ of known values and $x$ is a vector of length $n$ of unknown values.

We can solve this problem by expliciting finding the inverse matrix, $A^{-1}$. We saw in the lectures that if we use the matrix of cofactors method this is very inefficient, as the number of operations required grows as $n!$.

A more efficient method is Gaussian elimination. This notebook implements a version of this algorithm. The code below work on any sized matrix.

In [1]:
import numpy as np

In [2]:
def GaussianElimination(A, b, verboseLevel=0):
    n = A.shape[1]
    
    # Append the vector b as a column to the matrix A
    A1 = np.c_[A,b]
    
    if(verboseLevel >=1): print("A1 matrix =\n", A1, "\n")

    i = 0
    while i < n - 1:
        j = i+1
        while j < n:
            tmp = A1[i]*A1[j,i]/A1[i,i]
            if(verboseLevel >= 2): print("Row to subtract from a_%d" %j,"=", tmp)
            A1[j] = A1[j] - tmp
            j += 1
            
        if(verboseLevel >= 1): print("\nNew A1 matrix =\n", A1, "\n")
        i += 1
        
    # The matrix is now in upper-triangular form
    # Now we back substitute to find x
    
    x = np.zeros(n)
    
    i = n-1
    while i >= 0:
        j = i
        x[i] = A1[i,n]
        while j < n-1:
            x[i] -= A1[i,j+1]*x[j+1]
            j += 1
        x[i] = x[i]/A1[i,i]
        i -= 1
    
    return x

Let's first test the code on a $3\times 3$ matrix. I found testing on a small matrix like this was very useful to debug the code (it takes a while to get all the indexing correct).

In [3]:
# Define a matrix A, and a vector b
A1 = np.array([[1, 2, 3], [5, 6, 7], [1, 4, 5]], dtype='float')
b1 = np.array([3, 4 , 5])

# print out A and b (notice that '\n' creates a new line)
print("A =\n", A1)
print("\nb =", b1)

A =
 [[1. 2. 3.]
 [5. 6. 7.]
 [1. 4. 5.]]

b = [3 4 5]


The final argument to `GassianElimination()` is the `verboseLevel`. By default this is `0`. For higher values the code outputs more information about the steps it is taking.

In [4]:
x1 = GaussianElimination(A1, b1, 2)

A1 matrix =
 [[1. 2. 3. 3.]
 [5. 6. 7. 4.]
 [1. 4. 5. 5.]] 

Row to subtract from a_1 = [ 5. 10. 15. 15.]
Row to subtract from a_2 = [1. 2. 3. 3.]

New A1 matrix =
 [[  1.   2.   3.   3.]
 [  0.  -4.  -8. -11.]
 [  0.   2.   2.   2.]] 

Row to subtract from a_2 = [-0.   2.   4.   5.5]

New A1 matrix =
 [[  1.    2.    3.    3. ]
 [  0.   -4.   -8.  -11. ]
 [  0.    0.   -2.   -3.5]] 



Check the result, i.e., $A.x - b = 0$

In [5]:
np.dot(A1,x1) - b1

array([0., 0., 0.])

The `GaussianElimination()` function works for any size of matrix. Let's test it on a larger one.

In [6]:
# Define a matrix A, and a vector b
A2 = np.array([[1.3, 2.3, 3.7, 6.4, 7.7], [5, 6, 7, 1.4, 5.6], [1, 4, 5, 9.4, 1.5], [5.6, 6.6, 3.8, 4.5, 7.9], [3.4,7.7,8.3,9.1,9.3]], dtype='float') 
b2 = np.array([8, 4 , 3, 6, 9])

# print out A and b (notice that '\n' creates a new line)
print("A =\n", A2)
print("\nb =", b2)

A =
 [[1.3 2.3 3.7 6.4 7.7]
 [5.  6.  7.  1.4 5.6]
 [1.  4.  5.  9.4 1.5]
 [5.6 6.6 3.8 4.5 7.9]
 [3.4 7.7 8.3 9.1 9.3]]

b = [8 4 3 6 9]


In [7]:
## The below line sets the output precision when printing numpy arrays
np.set_printoptions(precision=3)

x2 = GaussianElimination(A2, b2, 2)
print(x2)

A1 matrix =
 [[1.3 2.3 3.7 6.4 7.7 8. ]
 [5.  6.  7.  1.4 5.6 4. ]
 [1.  4.  5.  9.4 1.5 3. ]
 [5.6 6.6 3.8 4.5 7.9 6. ]
 [3.4 7.7 8.3 9.1 9.3 9. ]] 

Row to subtract from a_1 = [ 5.     8.846 14.231 24.615 29.615 30.769]
Row to subtract from a_2 = [1.    1.769 2.846 4.923 5.923 6.154]
Row to subtract from a_3 = [ 5.6    9.908 15.938 27.569 33.169 34.462]
Row to subtract from a_4 = [ 3.4    6.015  9.677 16.738 20.138 20.923]

New A1 matrix =
 [[  1.3     2.3     3.7     6.4     7.7     8.   ]
 [  0.     -2.846  -7.231 -23.215 -24.015 -26.769]
 [  0.      2.231   2.154   4.477  -4.423  -3.154]
 [  0.     -3.308 -12.138 -23.069 -25.269 -28.462]
 [  0.      1.685  -1.377  -7.638 -10.838 -11.923]] 

Row to subtract from a_2 = [-0.     2.231  5.667 18.196 18.823 20.981]
Row to subtract from a_3 = [  0.     -3.308  -8.403 -26.98  -27.91  -31.11 ]
Row to subtract from a_4 = [-0.     1.685  4.28  13.741 14.215 15.844]

New A1 matrix =
 [[  1.3     2.3     3.7     6.4     7.7     8.   ]
 [  0. 

In [8]:
# Check the result
np.dot(A2,x2)-b2

array([ 0.000e+00, -1.332e-15, -2.220e-15, -1.776e-15, -7.105e-15])

## Near singular systems of equations

When is system of equations is very near singular, i.e., $|A| \sim$ 1e-16 rounding errors will be introduced and the final result may not be very accurate.

Let's look at an example.

In [19]:
A3 = np.array([[1+1e-14,2,3],[1,2,3],[5,6,8]])
b3 = np.array([4,7,5])

In [20]:
x3 = GaussianElimination(A3, b3)

In [21]:
np.dot(A3,x3) - b3

array([ 0.  , -0.25,  0.  ])

We see that $A.x - b \neq 0$. This is due to rounding errors.