# Matrix operations in Python with NumPy

In this notebook we look at the basic matrix and vector operations, such as inverse and dot product, with NumPy

In [34]:
import numpy as np
from numpy import linalg as la

## Vectors

In [35]:
a = np.array([1, 2])
b = np.array([3, 4])

If we multiply two vectors NumPy will multiply the components *element-wise*:

In [36]:
a*b

array([3, 8])

If instead we want to take the dot product we can use the `dot(a,b)` command

In [37]:
np.dot(a,b)

11

Compute the length of a vector

In [76]:
print(np.sqrt(np.dot(b,b)))
print(la.norm(b))

5.0
5.0


## Matrices

Let's define a $2\times2$ matrix. You can think of this is an array or arrays.

In [38]:
A = np.array([[1,2], [3,4]])

print(A)

[[1 2]
 [3 4]]


If we want to dot the matrix and the vector we again use the `dot()` function:

In [39]:
np.dot(A,b)

array([11, 25])

NumPy provides a lot of useful linear algebra operations in its `linalg` package. For example, to compute the inverse of a matrix we can use `linalg.inv()`

In [40]:
la.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Similarly, there is a function `linalg.det()` to compute the determinant of a matrix

In [41]:
la.det(A)

-2.0000000000000004

# Eigenvalues and eigenvectors

NumPy also provides functions to compute eigenvalues and eigenvectors. Recall these are the vectors and associated scalars that satisfy

$$ A.v = \lambda v$$

To compute both at once use the `eig()` function. This returns an array where the first element is an array of the eigenvalues, and the second is matrix where the **columns** are the eigenvectors

In [78]:
eigs = la.eig(A)

print("Eigenvalues = ", eigs[0])
print("Eigenvector 0 = ", eigs[1][:,0])
print("Eigenvector 1 = ", eigs[1][:,1])

Eigenvalues =  [-0.37228132  5.37228132]
Eigenvector 0 =  [-0.82456484  0.56576746]
Eigenvector 1 =  [-0.41597356 -0.90937671]


`eig()` returns unit normalized eigenvectors:

In [77]:
la.norm(eigs[1][:,0])

1.0

Check that the eigenvalue equation holds:

In [72]:
print(np.dot(A,eigs[1][:,0]))
print(eigs[0][0]*eigs[1][:,0])

[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]
