# PageRank and the power method

In the lectures we looked at an interesting usage for the power method for finding the maximum eigenvalue and the associated eigenvector: the PageRank algorithm. This notebook gives an example of the algorithm.

In [6]:
import numpy as np
from numpy import linalg as la

Load the MaxEigenvalue function: an implementation of the power method.

In [7]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    
    # Create a random initial vector
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        Ax      = A@x
        lamprev = lam
        lam = la.norm(Ax,2)/la.norm(x,2)
        x = Ax
        
    x = x/la.norm(x)
    return (lam,x)

In the lectures we consider a mini-network with four nodes and connections between them as follows:

<img src="images/MiniNetwork.png" width="300px">

We then saw that we cound find a solvable system by weighting the connections by the number of links from each node. We then had to solve problen of the form

$$ x = A x$$

This is an eigenvalue problem with eigenvalue 1. We also saw that the matrices formed as described above are known as column-stocastic matrices which means:

1) They have 1 as an eigenvalue
2) The absolute value of all other eigenvalues is less than 1.

This 1 is the maximum eigenvalue and we can use the power method to find the associated eigenvector.

In [8]:
A = np.array([[0,0.5,0.5,1/3.],[1,0,0,1/3.],[0,0,0,1/3.],[0,0.5,0.5,0]])

In [9]:
print(A)

[[0.         0.5        0.5        0.33333333]
 [1.         0.         0.         0.33333333]
 [0.         0.         0.         0.33333333]
 [0.         0.5        0.5        0.        ]]


In [14]:
res = MaxEigenvalue(A,1e-14)

In [22]:
print("The maximum eigenvalue is:", res[0])
print("The associated eigenvector is:", res[1])

The maximum eigenvalue is: 0.9999999999999958
The associated eigenvector is: [0.56011203 0.70014004 0.14002801 0.42008403]


From the above results we see that the second node is has the highest associated PageRank.

We can also find the eigenvectors from the linear algebra package of NumPy

In [23]:
eigensystem = la.eig(A)

In [33]:
print("The eigenvalues of A are given by:", eigensystem[0])
print("The eigenvector of the largest eigenvalue is:", eigensystem[1][:,0])

The eigenvalues of A are given by: [ 1.00000000e+00 -7.88675135e-01 -2.11324865e-01 -2.03356683e-17]
The eigenvector of the largest eigenvalue is: [-0.56011203 -0.70014004 -0.14002801 -0.42008403]
