# Matrix operations in Python with NumPy

In this notebook we look at the basic matrix and vector operations, such as inverse and dot product, with NumPy

In [1]:
import numpy as np

## Vectors

In [20]:
a = np.array([1, 2])
b = np.array([3, 4])

If we multiply two vectors NumPy will multiply the components *element-wise*:

In [21]:
a*b

array([3, 8])

If instead we want to take the dot product we can use the `dot(a,b)` command

In [22]:
np.dot(a,b)

11

## Matrices

Let's define a $2\times2$ matrix. You can think of this is an array or arrays.

In [23]:
A = np.array([[1,2], [3,4]])

print(A)

[[1 2]
 [3 4]]


If we want to dot the matrix and the vector we again use the `dot()` function:

In [24]:
np.dot(A,b)

array([11, 25])

NumPy provides a lot of useful linear algebra operations in its `linalg` package. For example, to compute the inverse of a matrix we can use `linalg.inv()`

In [25]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Similarly, there is a function `linalg.det()` to compute the determinant of a matrix

In [26]:
np.linalg.det(A)

-2.0000000000000004